Update stackhawk-scan.yml

diff --git a/.github/workflows/stackhawk-scan.yml b/.github/workflows/stackhawk-scan.yml
--- a/.github/workflows/stackhawk-scan.yml
+++ b/.github/workflows/stackhawk-scan.yml
@@ -12,13 +12,19 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - name: Install StackHawk CLI
+    - name: Check Network and Install StackHawk CLI
       run: |
         set -x
         mkdir -p $HOME/stackhawk
         curl -sL https://cli.stackhawk.com/install.sh -o $HOME/stackhawk/install.sh
         ls -al $HOME/stackhawk
         cat $HOME/stackhawk/install.sh  # Display the install script for debugging
+        echo "Checking connectivity to cli.stackhawk.com"
+        curl -I https://cli.stackhawk.com/install.sh
+        if [ $? -ne 0 ]; then
+          echo "Failed to reach cli.stackhawk.com"
+          exit 1
+        fi
         sh $HOME/stackhawk/install.sh || { echo "Install script failed"; exit 1; }
         ls -al $HOME/.hawk || echo "Directory $HOME/.hawk does not exist"
         if [ -d "$HOME/.hawk" ]; then
@@ -46,3 +52,4 @@ jobs:
       run: hawk scan
       env:
         HAWK_API_KEY: ${{ secrets.HAWK_API_KEY }}
+
